# -*- coding: utf-8 -*-
"""AVA Project EfficientNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAeTRiq2AblmxcduJxAbXezx9SpIJUhI
"""

from google.colab import drive
drive.mount('/content/drive')

import os, json, shutil, zipfile
import numpy as np
import pandas as pd

PROJECT_DIR    = '/content/drive/MyDrive/AVA_Project'
MODELS_DIR     = os.path.join(PROJECT_DIR, 'models')
CLASS_MAP_PATH = os.path.join(PROJECT_DIR, 'class_mapping.json')
LOCAL_DIR      = '/content/ava_local'
LOCAL_CROPS    = os.path.join(LOCAL_DIR, 'crops')
os.makedirs(MODELS_DIR,  exist_ok=True)
os.makedirs(LOCAL_DIR,   exist_ok=True)

# ── Zip crops on Drive (only once), then unzip locally ──────────
ZIP_PATH       = os.path.join(PROJECT_DIR, 'crops.zip')

if not os.path.exists(ZIP_PATH):
    print('📦 Zipping crops on Drive (one-time, ~2-3 min)...')
    shutil.make_archive(
        base_name=ZIP_PATH.replace('.zip', ''),
        format='zip',
        root_dir=os.path.dirname(os.path.join(PROJECT_DIR, 'crops')),
        base_dir='crops'
    )
    print('✅ Zip created on Drive')
else:
    print('✅ Zip already exists on Drive, skipping')

if not os.path.exists(LOCAL_CROPS):
    print('📂 Unzipping to local disk (~1 min)...')
    with zipfile.ZipFile(ZIP_PATH, 'r') as z:
        z.extractall(LOCAL_DIR)
    print('✅ Unzipped to local disk')
else:
    print('✅ Local crops already exist, skipping unzip')

# ── Fix manifest paths to point at local crops ──────────────────
for split in ['train', 'val']:
    dst = os.path.join(LOCAL_DIR, f'{split}_manifest.csv')
    if not os.path.exists(dst):
        df = pd.read_csv(os.path.join(PROJECT_DIR, f'{split}_manifest.csv'))
        df['path'] = df['path'].str.replace(
            os.path.join(PROJECT_DIR, 'crops'), LOCAL_CROPS, regex=False)
        df.to_csv(dst, index=False)

TRAIN_CSV = os.path.join(LOCAL_DIR, 'train_manifest.csv')
VAL_CSV   = os.path.join(LOCAL_DIR, 'val_manifest.csv')

with open(CLASS_MAP_PATH) as f:
    class_map = json.load(f)

IDX_TO_CLASS = {int(k): v for k, v in class_map['idx_to_class'].items()}
NUM_CLASSES  = class_map['num_classes']

print(f'\n✅ Ready — {NUM_CLASSES} classes')
print(f'   Train CSV: {TRAIN_CSV}')
print(f'   Val CSV:   {VAL_CSV}')

!pip install -q timm

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.metrics import classification_report, confusion_matrix, average_precision_score
from sklearn.preprocessing import label_binarize
from PIL import Image
from tqdm import tqdm
import timm
import matplotlib.pyplot as plt
import seaborn as sns

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'✅ Using device: {DEVICE}')
if DEVICE.type == 'cuda':
    print(f'   GPU: {torch.cuda.get_device_name(0)}')

class AVADataset(Dataset):
    def __init__(self, csv_path, transform=None):
        self.df        = pd.read_csv(csv_path)
        self.transform = transform
        self.df        = self.df[self.df['path'].apply(os.path.exists)].reset_index(drop=True)
        print(f'  Loaded {len(self.df)} samples')

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row   = self.df.iloc[idx]
        image = Image.open(row['path']).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, int(row['label'])

# ── CONFIG ─────────────────────────────────────
BATCH_SIZE  = 32    # smaller than CNN due to larger model
IMG_SIZE    = 224
NUM_WORKERS = 0
EPOCHS      = 12    # fewer than CNN's 20 but still comparable
# ───────────────────────────────────────────────

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.RandomGrayscale(p=0.05),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

train_dataset = AVADataset(TRAIN_CSV, transform=train_transform)
val_dataset   = AVADataset(VAL_CSV,   transform=val_transform)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=NUM_WORKERS, pin_memory=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=False)

print(f'\n✅ DataLoaders ready')
print(f'   Train: {len(train_dataset):,} samples, {len(train_loader)} batches')
print(f'   Val:   {len(val_dataset):,} samples,  {len(val_loader)} batches')

class EfficientNetAVA(nn.Module):
    """
    EfficientNet-B2 pretrained on ImageNet, fine-tuned for AVA action classification.

    Strategy:
      - Load EfficientNet-B2 with ImageNet weights (via timm)
      - Freeze early layers (stem + blocks 0-3) — keep low-level features
      - Fine-tune blocks 4-6 + head — adapt to action recognition
      - Replace classifier head with a custom 2-layer head + dropout

    Why B2 over B0?
      - B2 has stronger features than B0 but is lighter than B4/B7
      - Good balance of accuracy vs GPU memory for Colab T4
    """
    def __init__(self, num_classes, dropout=0.4):
        super().__init__()

        # Load pretrained EfficientNet-B2
        self.backbone = timm.create_model('efficientnet_b2', pretrained=True)

        # ── Freeze stem + first 4 blocks ──────────────────────────
        # We keep ImageNet low-level features frozen (edges, textures)
        # and only fine-tune the deeper, more semantic layers
        layers_to_freeze = [self.backbone.conv_stem,
                            self.backbone.bn1,
                            *list(self.backbone.blocks)[:4]]
        for layer in layers_to_freeze:
            for param in layer.parameters():
                param.requires_grad = False

        # ── Replace classifier head ────────────────────────────────
        in_features = self.backbone.classifier.in_features
        self.backbone.classifier = nn.Sequential(
            nn.Linear(in_features, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(512, num_classes)
        )

    def forward(self, x):
        return self.backbone(x)


model = EfficientNetAVA(num_classes=NUM_CLASSES).to(DEVICE)

total_params    = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'✅ EfficientNet-B2 ready')
print(f'   Total params:     {total_params:,}')
print(f'   Trainable params: {trainable_params:,}')
print(f'   Frozen params:    {total_params - trainable_params:,}')

LR           = 3e-4
WEIGHT_DECAY = 1e-4

# Class weights for imbalance
train_df     = pd.read_csv(TRAIN_CSV)
class_counts = train_df['label'].value_counts().sort_index().values
class_weights = torch.tensor(1.0 / class_counts, dtype=torch.float32).to(DEVICE)
class_weights = class_weights / class_weights.sum() * NUM_CLASSES

criterion = nn.CrossEntropyLoss(weight=class_weights)

# Two param groups: lower LR for unfrozen backbone, higher for new head
backbone_params = [p for name, p in model.named_parameters()
                   if p.requires_grad and 'classifier' not in name]
head_params     = [p for name, p in model.named_parameters()
                   if p.requires_grad and 'classifier' in name]

optimizer = optim.AdamW([
    {'params': backbone_params, 'lr': LR * 0.1},   # 3e-5 for backbone
    {'params': head_params,     'lr': LR}           # 3e-4 for head
], weight_decay=WEIGHT_DECAY)

# Warm up for 2 epochs then cosine decay
scheduler = optim.lr_scheduler.OneCycleLR(
    optimizer,
    max_lr=[LR * 0.1, LR],
    steps_per_epoch=len(train_loader),
    epochs=EPOCHS,
    pct_start=0.2   # 20% warmup
)

print(f'✅ Loss: CrossEntropyLoss (class-weighted)')
print(f'   Optimizer: AdamW — backbone lr={LR*0.1:.0e}, head lr={LR:.0e}')
print(f'   Scheduler: OneCycleLR with 20% warmup over {EPOCHS} epochs')

history         = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}
best_val_acc    = 0.0
best_model_path = os.path.join(MODELS_DIR, 'efficientnet_best.pth')

for epoch in range(1, EPOCHS + 1):

    # ── Train ──────────────────────────────────────────────────
    model.train()
    total_loss, correct, total = 0.0, 0, 0

    for i, (images, labels) in enumerate(train_loader):
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        scheduler.step()

        total_loss += loss.item() * images.size(0)
        correct    += (outputs.argmax(1) == labels).sum().item()
        total      += images.size(0)

        if (i + 1) % 20 == 0:
            print(f'  Epoch {epoch} | batch {i+1}/{len(train_loader)} '
                  f'| loss={total_loss/total:.4f} | acc={correct/total:.3f}', flush=True)

    train_loss = total_loss / total
    train_acc  = correct / total

    # ── Validate ───────────────────────────────────────────────
    model.eval()
    v_loss, v_correct, v_total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = model(images)
            v_loss    += criterion(outputs, labels).item() * images.size(0)
            v_correct += (outputs.argmax(1) == labels).sum().item()
            v_total   += images.size(0)

    val_loss = v_loss / v_total
    val_acc  = v_correct / v_total

    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), best_model_path)
        flag = '  ← best'
    else:
        flag = ''

    print(f'\nEpoch {epoch:2d}/{EPOCHS}  '
          f'train_loss={train_loss:.4f}  train_acc={train_acc:.3f}  '
          f'val_loss={val_loss:.4f}  val_acc={val_acc:.3f}{flag}\n', flush=True)

print(f'✅ Training complete — best val acc: {best_val_acc:.4f}')

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].plot(history['train_loss'], label='Train')
axes[0].plot(history['val_loss'],   label='Val')
axes[0].set_title('Loss')
axes[0].set_xlabel('Epoch')
axes[0].legend()

axes[1].plot(history['train_acc'], label='Train')
axes[1].plot(history['val_acc'],   label='Val')
axes[1].set_title('Accuracy')
axes[1].set_xlabel('Epoch')
axes[1].legend()

plt.suptitle('EfficientNet-B2 — Training Curves', fontsize=13)
plt.tight_layout()
plt.savefig(os.path.join(MODELS_DIR, 'efficientnet_curves.png'), dpi=150)
plt.show()

def full_evaluation(model, loader, num_classes, idx_to_class):
    model.eval()
    all_probs, all_preds, all_labels = [], [], []

    with torch.no_grad():
        for images, labels in tqdm(loader, desc='Evaluating'):
            images  = images.to(DEVICE)
            outputs = model(images)
            probs   = torch.softmax(outputs, dim=1)
            all_probs.append(probs.cpu().numpy())
            all_preds.extend(outputs.argmax(1).cpu().numpy())
            all_labels.extend(labels.numpy())

    all_probs  = np.concatenate(all_probs, axis=0)
    all_preds  = np.array(all_preds)
    all_labels = np.array(all_labels)

    # ── Accuracy ───────────────────────────────────────────────
    accuracy = (all_preds == all_labels).mean()

    # ── mAP ────────────────────────────────────────────────────
    labels_bin   = label_binarize(all_labels, classes=list(range(num_classes)))
    per_class_ap = {}
    for c in range(num_classes):
        if labels_bin[:, c].sum() == 0:
            continue
        ap = average_precision_score(labels_bin[:, c], all_probs[:, c])
        per_class_ap[idx_to_class[c]] = ap
    mAP = np.mean(list(per_class_ap.values()))

    return accuracy, mAP, per_class_ap, all_preds, all_labels


# Load best checkpoint
model.load_state_dict(torch.load(best_model_path, map_location=DEVICE))
accuracy, mAP, per_class_ap, preds, labels = full_evaluation(
    model, val_loader, NUM_CLASSES, IDX_TO_CLASS)

print(f'\n{"═"*52}')
print(f'  EfficientNet-B2 — Final Results')
print(f'{"═"*52}')
print(f'  Val Accuracy : {accuracy*100:.2f}%')
print(f'  mAP          : {mAP*100:.2f}%')
print(f'{"─"*52}')
print(f'\n  Per-class AP:')
for cls_name, ap in sorted(per_class_ap.items(), key=lambda x: -x[1]):
    bar = '█' * int(ap * 30)
    print(f'  {cls_name:<40} {ap:.4f}  {bar}')

print(f'\n{"─"*52}')
target_names = [IDX_TO_CLASS[i] for i in range(NUM_CLASSES)]
print(classification_report(labels, preds, target_names=target_names, zero_division=0))

cm = confusion_matrix(labels, preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names,
            yticklabels=target_names)
plt.title('EfficientNet-B2 — Confusion Matrix (Val Set)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.xticks(rotation=45, ha='right', fontsize=8)
plt.yticks(rotation=0, fontsize=8)
plt.tight_layout()
plt.savefig(os.path.join(MODELS_DIR, 'efficientnet_confusion.png'), dpi=150)
plt.show()

results = {
    'model':           'EfficientNet-B2',
    'best_val_acc':    round(float(accuracy), 4),
    'mAP':             round(float(mAP), 4),
    'epochs':          EPOCHS,
    'batch_size':      BATCH_SIZE,
    'lr':              LR,
    'num_classes':     NUM_CLASSES,
    'total_params':    total_params,
    'trainable_params':trainable_params,
    'per_class_ap':    {k: round(float(v), 4) for k, v in per_class_ap.items()},
    'history':         history
}

results_path = os.path.join(MODELS_DIR, 'efficientnet_results.json')
with open(results_path, 'w') as f:
    json.dump(results, f, indent=2)

# ── Side-by-side comparison ────────────────────────────────────
cnn_results_path = os.path.join(MODELS_DIR, 'baseline_cnn_results.json')
print(f'\n{"═"*52}')
print(f'  MODEL COMPARISON')
print(f'{"═"*52}')
print(f'  {"Metric":<20} {"Baseline CNN":>15} {"EfficientNet-B2":>16}')
print(f'{"─"*52}')

if os.path.exists(cnn_results_path):
    with open(cnn_results_path) as f:
        cnn = json.load(f)
    print(f'  {"Val Accuracy":<20} {cnn.get("best_val_acc",0)*100:>14.2f}% {accuracy*100:>15.2f}%')
    print(f'  {"mAP":<20} {cnn.get("mAP",0)*100:>14.2f}% {mAP*100:>15.2f}%')
    print(f'  {"Epochs":<20} {cnn.get("epochs","?"):>15} {EPOCHS:>16}')
    print(f'  {"Batch size":<20} {cnn.get("batch_size","?"):>15} {BATCH_SIZE:>16}')
    print(f'  {"Trainable params":<20} {cnn.get("params",0):>15,} {trainable_params:>16,}')
else:
    print('  (baseline_cnn_results.json not found — skipping comparison)')
    print(f'  {"Val Accuracy":<20} {"N/A":>15} {accuracy*100:>15.2f}%')
    print(f'  {"mAP":<20} {"N/A":>15} {mAP*100:>15.2f}%')

print(f'{"═"*52}')
print(f'✅ Results saved to {results_path}')
print(f'→  Next: Notebook 4 — SlowFast')