# -*- coding: utf-8 -*-
"""AVA_Project_Baseline_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KcWQliK8LOJUfGJ22lPv0VtbuBWrQvR
"""

from google.colab import drive
drive.mount('/content/drive')

import os, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_DIR    = '/content/drive/MyDrive/AVA_Project'
CLASS_MAP_PATH = os.path.join(PROJECT_DIR, 'class_mapping.json')
MODELS_DIR     = os.path.join(PROJECT_DIR, 'models')
os.makedirs(MODELS_DIR, exist_ok=True)

LOCAL_DIR   = '/content/ava_local'
LOCAL_CROPS = os.path.join(LOCAL_DIR, 'crops')
os.makedirs(LOCAL_DIR, exist_ok=True)

ZIP_PATH = os.path.join(PROJECT_DIR, 'crops.zip')

# ── Step 1: Zip crops on Drive (only needs to happen once ever) ──
if not os.path.exists(ZIP_PATH):
    print('🗜️  Zipping crops on Drive (one-time ~3-5 min)...')
    !cd "{PROJECT_DIR}" && zip -r crops.zip crops/
    print('✅ Zip saved to Drive')
else:
    print('✅ crops.zip already exists on Drive')

# ── Step 2: Unzip to local disk (fast, ~1-2 min) ────────────────
if not os.path.exists(LOCAL_CROPS):
    print('📦 Unzipping to local disk...')
    !unzip -q "{ZIP_PATH}" -d "{LOCAL_DIR}"
    print('✅ Unzipped to local disk')
else:
    print('✅ Local crops already exist')

# ── Step 3: Fix manifest paths ───────────────────────────────────
for split in ['train', 'val']:
    src = os.path.join(PROJECT_DIR, f'{split}_manifest.csv')
    dst = os.path.join(LOCAL_DIR,   f'{split}_manifest.csv')
    if not os.path.exists(dst):
        df = pd.read_csv(src)
        df['path'] = df['path'].str.replace(
            os.path.join(PROJECT_DIR, 'crops'),
            LOCAL_CROPS, regex=False
        )
        df.to_csv(dst, index=False)

TRAIN_CSV = os.path.join(LOCAL_DIR, 'train_manifest.csv')
VAL_CSV   = os.path.join(LOCAL_DIR, 'val_manifest.csv')

with open(CLASS_MAP_PATH) as f:
    class_map = json.load(f)

IDX_TO_CLASS = {int(k): v for k, v in class_map['idx_to_class'].items()}
NUM_CLASSES  = class_map['num_classes']
print(f'✅ Ready — {NUM_CLASSES} classes, reading from local disk')

!pip install -q torch torchvision scikit-learn

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from sklearn.metrics import classification_report, confusion_matrix
from PIL import Image
from tqdm import tqdm

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'✅ Using device: {DEVICE}')
if DEVICE.type == 'cuda':
    print(f'   GPU: {torch.cuda.get_device_name(0)}')

class AVADataset(Dataset):
    def __init__(self, csv_path, transform=None, max_samples_per_class=None):
        df = pd.read_csv(csv_path)
        df = df[df['path'].apply(os.path.exists)].reset_index(drop=True)

        # Subsample per class to keep dataset small and balanced
        if max_samples_per_class:
            df = (df.groupby('label')
                    .apply(lambda x: x.sample(min(len(x), max_samples_per_class),
                                               random_state=42))
                    .reset_index(drop=True))

        self.df        = df
        self.transform = transform
        print(f'  Loaded {len(self.df)} samples ({csv_path.split("/")[-1]})')

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row   = self.df.iloc[idx]
        image = Image.open(row['path']).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, int(row['label'])

# ── CONFIG ────────────────────────────────────
BATCH_SIZE  = 64   # larger batch = fewer iterations per epoch
IMG_SIZE    = 224
NUM_WORKERS = 0    # 0 = no multiprocessing, avoids Colab deadlocks
# ──────────────────────────────────────────────

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

train_dataset = AVADataset(TRAIN_CSV, transform=train_transform)
val_dataset   = AVADataset(VAL_CSV,   transform=val_transform)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=NUM_WORKERS, pin_memory=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=False)

print(f'✅ DataLoaders ready')
print(f'   Train: {len(train_dataset)} samples, {len(train_loader)} batches')
print(f'   Val:   {len(val_dataset)} samples, {len(val_loader)} batches')

class BaselineCNN(nn.Module):
    """
    A from-scratch CNN with 4 convolutional blocks.
    Deliberately simple — this is our baseline to beat with EfficientNet and SlowFast.

    Architecture:
      Block 1: Conv(3→32)   → BN → ReLU → MaxPool
      Block 2: Conv(32→64)  → BN → ReLU → MaxPool
      Block 3: Conv(64→128) → BN → ReLU → MaxPool
      Block 4: Conv(128→256)→ BN → ReLU → AdaptiveAvgPool
      Head:    FC(256→512) → Dropout → FC(512→num_classes)
    """
    def __init__(self, num_classes):
        super().__init__()

        def conv_block(in_ch, out_ch):
            return nn.Sequential(
                nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1, bias=False),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
                nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1, bias=False),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
                nn.MaxPool2d(2, 2)
            )

        self.features = nn.Sequential(
            conv_block(3,   32),   # 224 → 112
            conv_block(32,  64),   # 112 → 56
            conv_block(64,  128),  # 56  → 28
            conv_block(128, 256),  # 28  → 14
            nn.AdaptiveAvgPool2d((4, 4))  # → 256×4×4 = 4096
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256 * 4 * 4, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )

    def forward(self, x):
        return self.classifier(self.features(x))


model = BaselineCNN(num_classes=NUM_CLASSES).to(DEVICE)

# Count parameters
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'✅ BaselineCNN ready — {total_params:,} trainable parameters')
print(model)

# ── TRAINING CONFIG ───────────────────────────
EPOCHS        = 20
LR            = 1e-3
WEIGHT_DECAY  = 1e-4
# ──────────────────────────────────────────────

# Compute class weights to handle imbalance
train_df     = pd.read_csv(TRAIN_CSV)
class_counts = train_df['label'].value_counts().sort_index().values
class_weights = torch.tensor(1.0 / class_counts, dtype=torch.float32).to(DEVICE)
class_weights = class_weights / class_weights.sum() * NUM_CLASSES  # normalize

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = optim.Adam(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

print(f'✅ Loss: CrossEntropyLoss (class-weighted)')
print(f'   Optimizer: Adam  lr={LR}  weight_decay={WEIGHT_DECAY}')
print(f'   Scheduler: CosineAnnealingLR over {EPOCHS} epochs')

def train_one_epoch(model, loader, criterion, optimizer):
    model.train()
    total_loss, correct, total = 0.0, 0, 0
    for images, labels in loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * images.size(0)
        correct    += (outputs.argmax(1) == labels).sum().item()
        total      += images.size(0)
    return total_loss / total, correct / total


def evaluate(model, loader, criterion):
    model.eval()
    total_loss, correct, total = 0.0, 0, 0
    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = model(images)
            loss    = criterion(outputs, labels)
            total_loss += loss.item() * images.size(0)
            preds       = outputs.argmax(1)
            correct    += (preds == labels).sum().item()
            total      += images.size(0)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    return total_loss / total, correct / total, all_preds, all_labels

print('✅ Training functions defined')

history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}
best_val_acc    = 0.0
best_model_path = os.path.join(MODELS_DIR, 'baseline_cnn_best.pth')

for epoch in range(1, EPOCHS + 1):
    # ── Train ──────────────────────────────────────────────────
    model.train()
    total_loss, correct, total = 0.0, 0, 0
    for i, (images, labels) in enumerate(train_loader):
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * images.size(0)
        correct    += (outputs.argmax(1) == labels).sum().item()
        total      += images.size(0)

        # Print progress every 20 batches so you know it's alive
        if (i + 1) % 20 == 0:
            print(f'  Epoch {epoch} | batch {i+1}/{len(train_loader)} '
                  f'| loss={total_loss/total:.4f} | acc={correct/total:.3f}', flush=True)

    train_loss = total_loss / total
    train_acc  = correct / total

    # ── Validate ───────────────────────────────────────────────
    model.eval()
    v_loss, v_correct, v_total = 0.0, 0, 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = model(images)
            loss    = criterion(outputs, labels)
            v_loss     += loss.item() * images.size(0)
            v_correct  += (outputs.argmax(1) == labels).sum().item()
            v_total    += images.size(0)
    val_loss = v_loss / v_total
    val_acc  = v_correct / v_total
    scheduler.step()

    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), best_model_path)
        flag = '  ← best'
    else:
        flag = ''

    print(f'\nEpoch {epoch:2d}/{EPOCHS}  '
          f'train_loss={train_loss:.4f}  train_acc={train_acc:.3f}  '
          f'val_loss={val_loss:.4f}  val_acc={val_acc:.3f}{flag}\n', flush=True)

print(f'\n✅ Training complete. Best val acc: {best_val_acc:.3f}')

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].plot(history['train_loss'], label='Train')
axes[0].plot(history['val_loss'],   label='Val')
axes[0].set_title('Loss')
axes[0].set_xlabel('Epoch')
axes[0].legend()

axes[1].plot(history['train_acc'], label='Train')
axes[1].plot(history['val_acc'],   label='Val')
axes[1].set_title('Accuracy')
axes[1].set_xlabel('Epoch')
axes[1].legend()

plt.suptitle('Baseline CNN — Training Curves', fontsize=13)
plt.tight_layout()
plt.savefig(os.path.join(MODELS_DIR, 'baseline_cnn_curves.png'), dpi=150)
plt.show()

# Load best checkpoint
model.load_state_dict(torch.load(best_model_path))
_, val_acc, preds, labels = evaluate(model, val_loader, criterion)

print(f'✅ Best model val accuracy: {val_acc:.4f} ({val_acc*100:.2f}%)\n')

target_names = [IDX_TO_CLASS[i] for i in range(NUM_CLASSES)]
print(classification_report(labels, preds, target_names=target_names, zero_division=0))

cm = confusion_matrix(labels, preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names,
            yticklabels=target_names)
plt.title('Baseline CNN — Confusion Matrix (Val Set)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.xticks(rotation=45, ha='right', fontsize=8)
plt.yticks(rotation=0, fontsize=8)
plt.tight_layout()
plt.savefig(os.path.join(MODELS_DIR, 'baseline_cnn_confusion.png'), dpi=150)
plt.show()

results = {
    'model':        'BaselineCNN',
    'best_val_acc': round(best_val_acc, 4),
    'epochs':       EPOCHS,
    'batch_size':   BATCH_SIZE,
    'lr':           LR,
    'num_classes':  NUM_CLASSES,
    'params':       total_params,
    'history':      history
}

results_path = os.path.join(MODELS_DIR, 'baseline_cnn_results.json')
with open(results_path, 'w') as f:
    json.dump(results, f, indent=2)

print(f'✅ Results saved to {results_path}')
print(f'\n─── BASELINE CNN SUMMARY ───────────────────')
print(f'   Val Accuracy:  {best_val_acc*100:.2f}%')
print(f'   Parameters:    {total_params:,}')
print(f'   Epochs:        {EPOCHS}')
print(f'────────────────────────────────────────────')
print(f'→ Next: Notebook 3 — EfficientNet')

from google.colab import drive
drive.mount('/content/drive')

import os, json, torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from tqdm import tqdm

PROJECT_DIR    = '/content/drive/MyDrive/AVA_Project'
MODELS_DIR     = os.path.join(PROJECT_DIR, 'models')
CLASS_MAP_PATH = os.path.join(PROJECT_DIR, 'class_mapping.json')

with open(CLASS_MAP_PATH) as f:
    class_map = json.load(f)

IDX_TO_CLASS = {int(k): v for k, v in class_map['idx_to_class'].items()}
NUM_CLASSES  = class_map['num_classes']
DEVICE       = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(f'✅ Config loaded — {NUM_CLASSES} classes, device: {DEVICE}')

import torch.nn as nn

class BaselineCNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        def conv_block(in_ch, out_ch):
            return nn.Sequential(
                nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1, bias=False),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
                nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1, bias=False),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
                nn.MaxPool2d(2, 2)
            )
        self.features = nn.Sequential(
            conv_block(3,   32),
            conv_block(32,  64),
            conv_block(64,  128),
            conv_block(128, 256),
            nn.AdaptiveAvgPool2d((4, 4))
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256 * 4 * 4, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )
    def forward(self, x):
        return self.classifier(self.features(x))

model           = BaselineCNN(num_classes=NUM_CLASSES).to(DEVICE)
best_model_path = os.path.join(MODELS_DIR, 'baseline_cnn_best.pth')
model.load_state_dict(torch.load(best_model_path, map_location=DEVICE))
model.eval()
print(f'✅ Model loaded from {best_model_path}')

LOCAL_DIR   = '/content/ava_local'
LOCAL_CROPS = os.path.join(LOCAL_DIR, 'crops')

import shutil
if not os.path.exists(LOCAL_CROPS):
    print('📦 Copying crops to local disk (~2-3 min)...')
    shutil.copytree(os.path.join(PROJECT_DIR, 'crops'), LOCAL_CROPS)
    print('✅ Done')
else:
    print('✅ Local crops already exist')

# ── Rebuild val manifest with corrected paths ──────────────────
# Read original from Drive (always use this as source of truth)
df = pd.read_csv(os.path.join(PROJECT_DIR, 'val_manifest.csv'))

# Find what the paths currently say and replace the Drive prefix with local
old_prefix = df['path'].iloc[0].rsplit('/crops/', 1)[0] + '/crops'
new_prefix = LOCAL_CROPS
df['path'] = df['path'].str.replace(old_prefix, new_prefix, regex=False)

VAL_CSV = os.path.join(LOCAL_DIR, 'val_manifest.csv')
df.to_csv(VAL_CSV, index=False)

# Verify a few paths actually exist
sample_paths = df['path'].head(5).tolist()
print('\nPath check:')
for p in sample_paths:
    print(f'  {"✅" if os.path.exists(p) else "❌"} {p}')

class AVADataset(Dataset):
    def __init__(self, csv_path, transform=None):
        self.df        = pd.read_csv(csv_path)
        self.transform = transform
        self.df        = self.df[self.df['path'].apply(os.path.exists)].reset_index(drop=True)
        print(f'  Loaded {len(self.df)} val samples')
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        row   = self.df.iloc[idx]
        image = Image.open(row['path']).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, int(row['label'])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

val_dataset = AVADataset(VAL_CSV, transform=val_transform)
val_loader  = DataLoader(val_dataset, batch_size=64, shuffle=False,
                         num_workers=0, pin_memory=False)
print(f'✅ Val loader ready — {len(val_loader)} batches')

from sklearn.preprocessing import label_binarize
from sklearn.metrics import average_precision_score, classification_report, confusion_matrix

def compute_map(model, loader, num_classes, idx_to_class):
    model.eval()
    all_probs, all_labels = [], []
    with torch.no_grad():
        for images, labels in tqdm(loader, desc='Computing mAP'):
            images = images.to(DEVICE)
            probs  = torch.softmax(model(images), dim=1)
            all_probs.append(probs.cpu().numpy())
            all_labels.append(labels.numpy())

    all_probs  = np.concatenate(all_probs,  axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    labels_bin = label_binarize(all_labels, classes=list(range(num_classes)))

    per_class_ap = {}
    for c in range(num_classes):
        if labels_bin[:, c].sum() == 0:
            continue
        ap = average_precision_score(labels_bin[:, c], all_probs[:, c])
        per_class_ap[idx_to_class[c]] = ap

    return np.mean(list(per_class_ap.values())), per_class_ap

mAP, per_class_ap = compute_map(model, val_loader, NUM_CLASSES, IDX_TO_CLASS)

print(f'\n{"─"*50}')
print(f'  Baseline CNN mAP: {mAP*100:.2f}%')
print(f'{"─"*50}')
print(f'\n  Per-class AP:')
for cls_name, ap in sorted(per_class_ap.items(), key=lambda x: -x[1]):
    bar = '█' * int(ap * 30)
    print(f'  {cls_name:<40} {ap:.4f}  {bar}')

results_path = os.path.join(MODELS_DIR, 'baseline_cnn_results.json')

# Load existing results if they exist, otherwise start fresh
if os.path.exists(results_path):
    with open(results_path) as f:
        results = json.load(f)
    print('✅ Loaded existing results, adding mAP...')
else:
    results = {}
    print('⚠️  No existing results file found, creating new one...')

results['mAP']          = round(float(mAP), 4)
results['per_class_ap'] = {k: round(float(v), 4) for k, v in per_class_ap.items()}

with open(results_path, 'w') as f:
    json.dump(results, f, indent=2)

print(f'✅ Saved to {results_path}')
print(f'\n  Final summary:')
print(f'  Accuracy: {results.get("best_val_acc", "N/A")}')
print(f'  mAP:      {results["mAP"]}')