# -*- coding: utf-8 -*-
"""AVA Project Prep Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CU5z2GsSzyhF4rXA2lNRV1lEWwQPR8MY
"""

from google.colab import drive
drive.mount('/content/drive')

import os

PROJECT_DIR     = '/content/drive/MyDrive/AVA_Project'
ANNOTATIONS_DIR = os.path.join(PROJECT_DIR, 'annotations')
VIDEOS_DIR      = os.path.join(PROJECT_DIR, 'videos')
FRAMES_DIR      = os.path.join(PROJECT_DIR, 'frames')
CROPS_DIR       = os.path.join(PROJECT_DIR, 'crops')

for d in [ANNOTATIONS_DIR, VIDEOS_DIR, FRAMES_DIR, CROPS_DIR]:
    os.makedirs(d, exist_ok=True)

print('✅ Directory structure ready')

!pip install -q yt-dlp
!pip install -q pandas numpy opencv-python-headless matplotlib seaborn tqdm Pillow

import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm import tqdm
import shutil, json, glob, re, subprocess

# Verify ffmpeg
!ffmpeg -version 2>&1 | head -1
print('✅ Dependencies ready')

import urllib.request

FILES = {
    'ava_train_v2.2.csv': 'https://storage.googleapis.com/download.tensorflow.org/data/ava_train_v2.2.csv',
    'ava_val_v2.2.csv':   'https://storage.googleapis.com/download.tensorflow.org/data/ava_val_v2.2.csv',
    'ava_action_list_v2.2.pbtxt': 'https://raw.githubusercontent.com/cvdfoundation/ava-dataset/main/ava_action_list_v2.2.pbtxt',
}

for fname, url in FILES.items():
    dest = os.path.join(ANNOTATIONS_DIR, fname)
    if os.path.exists(dest):
        print(f'  ⏭️  Already exists: {fname}')
    else:
        print(f'  ⬇️  Downloading {fname}...')
        urllib.request.urlretrieve(url, dest)
        print(f'  ✅ Done')

print('\n✅ All annotation files downloaded')

def parse_label_map(pbtxt_path):
    label_map = {}
    with open(pbtxt_path, 'r') as f:
        content = f.read()
    entries = re.findall(r'label\s*\{([^}]+)\}', content, re.DOTALL)
    for entry in entries:
        name_match = re.search(r'name:\s*"([^"]+)"', entry)
        id_match   = re.search(r'label_id:\s*(\d+)', entry)
        if name_match and id_match:
            label_map[int(id_match.group(1))] = name_match.group(1)
    return label_map

ACTION_MAP = parse_label_map(os.path.join(ANNOTATIONS_DIR, 'ava_action_list_v2.2.pbtxt'))
print(f'✅ Parsed {len(ACTION_MAP)} action classes:')
for k, v in sorted(ACTION_MAP.items()):
    print(f'  {k:3d}: {v}')

CSV_COLS = ['video_id', 'timestamp', 'x1', 'y1', 'x2', 'y2', 'action_id', 'person_id']

train_df = pd.read_csv(os.path.join(ANNOTATIONS_DIR, 'ava_train_v2.2.csv'), header=None, names=CSV_COLS)
val_df   = pd.read_csv(os.path.join(ANNOTATIONS_DIR, 'ava_val_v2.2.csv'),   header=None, names=CSV_COLS)

train_df['action_name'] = train_df['action_id'].map(ACTION_MAP)
val_df['action_name']   = val_df['action_id'].map(ACTION_MAP)

print('─── TRAINING SET ───')
print(f'  Rows:          {len(train_df):,}')
print(f'  Unique videos: {train_df["video_id"].nunique()}')
print(f'  Unique actions:{train_df["action_id"].nunique()}')
print()
print('─── VALIDATION SET ─')
print(f'  Rows:          {len(val_df):,}')
print(f'  Unique videos: {val_df["video_id"].nunique()}')
print(f'  Unique actions:{val_df["action_id"].nunique()}')
print()
train_df.head()

top_classes = train_df['action_name'].value_counts().head(25)

plt.figure(figsize=(13, 6))
sns.barplot(x=top_classes.values, y=top_classes.index, palette='viridis')
plt.title('Top 25 Most Frequent Classes in AVA Train (all 235 videos)')
plt.xlabel('Annotation count')
plt.tight_layout()
plt.show()

# ── CONFIG ────────────────────────────────────────────
NUM_TRAIN_VIDEOS = 15
NUM_VAL_VIDEOS   = 5
TOP_N_CLASSES    = 15   # keep the top 15 most frequent classes
# ──────────────────────────────────────────────────────

def select_diverse_videos(df, n_videos, min_annotations=100):
    """
    Greedy set-cover: pick videos that together cover the most unique action classes.
    Prefers videos with more annotations.
    """
    video_stats = (
        df.groupby('video_id')
          .agg(
              annotation_count=('action_id', 'count'),
              class_set=('action_id', lambda x: frozenset(x))
          )
          .reset_index()
    )
    video_stats = video_stats[video_stats['annotation_count'] >= min_annotations]

    selected      = []
    covered       = set()

    for _ in range(n_videos):
        best_vid, best_new, best_set = None, -1, set()
        for _, row in video_stats.iterrows():
            if row['video_id'] in selected:
                continue
            new = len(row['class_set'] - covered)
            if new > best_new:
                best_new, best_vid, best_set = new, row['video_id'], row['class_set']
        if best_vid is None:
            break
        selected.append(best_vid)
        covered |= best_set

    print(f'Selected {len(selected)} videos covering {len(covered)} unique classes')
    return selected


TRAIN_VIDEO_IDS = select_diverse_videos(train_df, NUM_TRAIN_VIDEOS)
VAL_VIDEO_IDS   = select_diverse_videos(val_df,   NUM_VAL_VIDEOS)

print('\n📹 TRAIN videos:')
for v in TRAIN_VIDEO_IDS:
    n = len(train_df[train_df['video_id'] == v])
    c = train_df[train_df['video_id'] == v]['action_id'].nunique()
    print(f'   {v}  —  {n} annotations, {c} classes')

print('\n📹 VAL videos:')
for v in VAL_VIDEO_IDS:
    n = len(val_df[val_df['video_id'] == v])
    c = val_df[val_df['video_id'] == v]['action_id'].nunique()
    print(f'   {v}  —  {n} annotations, {c} classes')

train_sub = train_df[train_df['video_id'].isin(TRAIN_VIDEO_IDS)].copy()
val_sub   = val_df[val_df['video_id'].isin(VAL_VIDEO_IDS)].copy()

# Top-N classes by frequency in our training subset
top_class_ids   = train_sub['action_id'].value_counts().head(TOP_N_CLASSES).index.tolist()
top_class_names = [ACTION_MAP[i] for i in top_class_ids]

print(f'Keeping top {TOP_N_CLASSES} classes:')
for i, (cid, cname) in enumerate(zip(top_class_ids, top_class_names)):
    count = (train_sub['action_id'] == cid).sum()
    print(f'  {i:2d}. [{cid:2d}] {cname:<40} ({count} annotations)')

# Build 0-based label index
CLASS_TO_IDX = {cid: idx for idx, cid in enumerate(top_class_ids)}
IDX_TO_CLASS = {idx: ACTION_MAP[cid] for cid, idx in CLASS_TO_IDX.items()}

# Filter & remap
train_sub = train_sub[train_sub['action_id'].isin(top_class_ids)].copy()
val_sub   = val_sub[val_sub['action_id'].isin(top_class_ids)].copy()
train_sub['label'] = train_sub['action_id'].map(CLASS_TO_IDX)
val_sub['label']   = val_sub['action_id'].map(CLASS_TO_IDX)

print(f'\nTrain annotations after filtering: {len(train_sub):,}')
print(f'Val   annotations after filtering: {len(val_sub):,}')

def download_video(video_id, output_dir):
    url = f'https://www.youtube.com/watch?v={video_id}'
    out = os.path.join(output_dir, f'{video_id}.mp4')

    if os.path.exists(out):
        print(f'  ⏭️  {video_id}: already downloaded')
        return out

    cmd = [
        'yt-dlp',
        '--format', 'bestvideo[height<=360][ext=mp4]+bestaudio[ext=m4a]/best[height<=360]',
        '--merge-output-format', 'mp4',
        '--output', out,
        '--no-playlist', '--quiet', '--no-warnings',
        url
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode == 0 and os.path.exists(out):
            size_mb = os.path.getsize(out) / (1024**2)
            print(f'  ✅ {video_id}: {size_mb:.1f} MB')
            return out
        print(f'  ❌ {video_id}: failed — {result.stderr[:120]}')
        return None
    except Exception as e:
        print(f'  ❌ {video_id}: {e}')
        return None


def download_until_target(all_candidates, output_dir, target, label):
    """
    Try candidates in order, keep going until we have `target` successful downloads.
    `all_candidates` is the full ranked list from select_diverse_videos.
    """
    downloaded = {}
    print(f'=== Downloading {label} videos (need {target}) ===')
    for vid in all_candidates:
        if len(downloaded) >= target:
            break
        path = download_video(vid, output_dir)
        if path:
            downloaded[vid] = path
    print(f'  → Got {len(downloaded)}/{target}\n')
    return downloaded


# Re-run selection but ask for a much larger candidate pool to draw from
TRAIN_CANDIDATES = select_diverse_videos(train_df, 60)  # big pool
VAL_CANDIDATES   = select_diverse_videos(val_df,   30)

downloaded_train = download_until_target(TRAIN_CANDIDATES, VIDEOS_DIR, 15, 'TRAIN')
downloaded_val   = download_until_target(VAL_CANDIDATES,   VIDEOS_DIR, 5,  'VAL')

# Update subsets to only successfully downloaded videos
train_sub = train_sub[train_sub['video_id'].isin(downloaded_train)]
val_sub   = val_sub[val_sub['video_id'].isin(downloaded_val)]

print(f'✅ Final: {len(downloaded_train)} train, {len(downloaded_val)} val videos')
print(f'   Train annotations: {len(train_sub):,} | Val: {len(val_sub):,}')

def extract_frame(video_path, timestamp_sec, output_path):
    if os.path.exists(output_path):
        return True
    cmd = [
        'ffmpeg', '-ss', str(int(timestamp_sec)),
        '-i', video_path,
        '-frames:v', '1', '-q:v', '2', '-y',
        output_path
    ]
    r = subprocess.run(cmd, capture_output=True)
    return r.returncode == 0 and os.path.exists(output_path)


# Only process videos we actually downloaded successfully
all_videos = {vid: path for vid, path in {**downloaded_train, **downloaded_val}.items()
              if os.path.exists(path)}
print(f'Processing {len(all_videos)} videos with confirmed local files\n')

# ── KEY FIX: rebuild annotations from the FULL original dataframes ──────────
# train_sub/val_sub were filtered to the original selected IDs — extra
# downloaded videos have no rows there. Pull from train_df/val_df instead,
# then apply the same class filter and label remapping.
all_annots = pd.concat([
    train_df[train_df['video_id'].isin(downloaded_train)],
    val_df[val_df['video_id'].isin(downloaded_val)]
])
all_annots = all_annots[all_annots['action_id'].isin(top_class_ids)].copy()
all_annots['label'] = all_annots['action_id'].map(CLASS_TO_IDX)

# Rebuild train_sub and val_sub so later cells stay consistent
train_sub = all_annots[all_annots['video_id'].isin(downloaded_train)].copy()
val_sub   = all_annots[all_annots['video_id'].isin(downloaded_val)].copy()
print(f'Rebuilt — train annotations: {len(train_sub):,} | val: {len(val_sub):,}\n')

frame_map = {}

for video_id, video_path in tqdm(all_videos.items(), desc='Videos'):
    vid_dir = os.path.join(FRAMES_DIR, video_id)
    os.makedirs(vid_dir, exist_ok=True)

    timestamps = all_annots[all_annots['video_id'] == video_id]['timestamp'].unique()

    if len(timestamps) == 0:
        print(f'  ⚠️  {video_id}: still no annotations after rebuild — skipping')
        continue

    fmap = {}
    for ts in timestamps:
        out = os.path.join(vid_dir, f'{int(ts):04d}.jpg')
        if extract_frame(video_path, ts, out):
            fmap[ts] = out

    frame_map[video_id] = fmap
    print(f'  {video_id}: {len(fmap)}/{len(timestamps)} frames extracted')

print(f'\n✅ Frame extraction complete — {len(frame_map)} videos, '
      f'{sum(len(v) for v in frame_map.values()):,} total frames')

CROP_SIZE = 224
PADDING   = 0.10

def crop_and_save(frame_path, row, output_path):
    if os.path.exists(output_path):
        return True
    img = cv2.imread(frame_path)
    if img is None:
        return False
    H, W = img.shape[:2]
    x1 = max(0, int((row['x1'] - PADDING) * W))
    y1 = max(0, int((row['y1'] - PADDING) * H))
    x2 = min(W, int((row['x2'] + PADDING) * W))
    y2 = min(H, int((row['y2'] + PADDING) * H))
    if x2 - x1 < 10 or y2 - y1 < 10:
        return False
    crop = cv2.resize(img[y1:y2, x1:x2], (CROP_SIZE, CROP_SIZE), interpolation=cv2.INTER_LANCZOS4)
    cv2.imwrite(output_path, crop)
    return True


def build_crops(df_sub, split_name):
    manifest = []
    for _, row in tqdm(df_sub.iterrows(), total=len(df_sub), desc=f'Cropping {split_name}'):
        vid, ts = row['video_id'], row['timestamp']
        if vid not in frame_map or ts not in frame_map[vid]:
            continue
        cls_folder = row['action_name'].replace('/', '_').replace(' ', '_').replace('(','').replace(')','')
        cls_dir    = os.path.join(CROPS_DIR, split_name, cls_folder)
        os.makedirs(cls_dir, exist_ok=True)
        fname      = f"{vid}_{int(ts):04d}_{int(row['person_id'])}.jpg"
        out_path   = os.path.join(cls_dir, fname)
        if crop_and_save(frame_map[vid][ts], row, out_path):
            manifest.append({
                'path': out_path, 'label': int(row['label']),
                'class_name': row['action_name'], 'video_id': vid,
                'timestamp': int(ts), 'person_id': int(row['person_id'])
            })
    return manifest


train_manifest = build_crops(train_sub, 'train')
val_manifest   = build_crops(val_sub,   'val')
print(f'\n✅ Crops — Train: {len(train_manifest):,}, Val: {len(val_manifest):,}')

train_manifest_df = pd.DataFrame(train_manifest)
val_manifest_df   = pd.DataFrame(val_manifest)

train_csv = os.path.join(PROJECT_DIR, 'train_manifest.csv')
val_csv   = os.path.join(PROJECT_DIR, 'val_manifest.csv')
train_manifest_df.to_csv(train_csv, index=False)
val_manifest_df.to_csv(val_csv,   index=False)

class_map_path = os.path.join(PROJECT_DIR, 'class_mapping.json')
with open(class_map_path, 'w') as f:
    json.dump({
        'idx_to_class': {str(k): v for k, v in IDX_TO_CLASS.items()},
        'num_classes':  len(IDX_TO_CLASS)
    }, f, indent=2)

print('✅ Saved:')
print(f'   {train_csv}')
print(f'   {val_csv}')
print(f'   {class_map_path}')
train_manifest_df.head()

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
for ax, df, title in [
    (axes[0], train_manifest_df, 'Train'),
    (axes[1], val_manifest_df,   'Val')
]:
    counts = df['class_name'].value_counts()
    sns.barplot(x=counts.values, y=counts.index, ax=ax, palette='magma')
    ax.set_title(f'{title} — Class Distribution (n={len(df):,})')
    ax.set_xlabel('Crop count')
plt.tight_layout()
plt.show()

classes  = train_manifest_df['class_name'].unique()[:12]
fig, axes = plt.subplots(4, 6, figsize=(15, 10))
axes = axes.flatten()

idx = 0
for cls in classes:
    samples = train_manifest_df[train_manifest_df['class_name'] == cls].sample(min(2, len(train_manifest_df[train_manifest_df['class_name'] == cls])))
    for _, row in samples.iterrows():
        if idx >= len(axes): break
        img = cv2.imread(row['path'])
        if img is not None:
            axes[idx].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        axes[idx].set_title(cls[:22], fontsize=7)
        axes[idx].axis('off')
        idx += 1

for ax in axes[idx:]:
    ax.axis('off')

plt.suptitle('Sample Crops from AVA Subset', fontsize=13)
plt.tight_layout()
plt.show()

print('=' * 50)
print('  AVA MINI-DATASET — COMPLETE')
print('=' * 50)
print(f'  Train videos:  {len(downloaded_train)}')
print(f'  Val videos:    {len(downloaded_val)}')
print(f'  Classes:       {len(IDX_TO_CLASS)}')
print(f'  Train crops:   {len(train_manifest_df):,}')
print(f'  Val crops:     {len(val_manifest_df):,}')
print()
print('  Class breakdown:')
for idx, name in IDX_TO_CLASS.items():
    tr = len(train_manifest_df[train_manifest_df['label'] == idx])
    vl = len(val_manifest_df[val_manifest_df['label'] == idx]) if len(val_manifest_df) > 0 else 0
    print(f'    [{idx:2d}] {name:<35} train={tr:4d}  val={vl:4d}')
print()
print('  ✅ Ready for Notebook 2: Baseline CNN')
print('=' * 50)